# Maven

trigger:
- master

strategy:
  matrix:
    linux:
      imageName: "ubuntu-16.04"
#    mac:
#      imageName: "macos-10.14"
#    windows:
#      imageName: "vs2017-win2016"
  maxParallel: 3

pool:
  vmImage: $(imageName)

steps:

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      [xml]$pomXml = Get-Content .\pom.xml
      # version
      Write-Host $pomXml.project.version
      $version=$pomXml.project.version
      Write-Host "##vso[task.setvariable variable=version]$version"
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package cobertura:cobertura'

  # Publish code coverage results
  # Publish JaCoCo code coverage results from a build
#- task: PublishCodeCoverageResults@1
#  inputs:
#    codeCoverageTool: "JaCoCo"
#    summaryFileLocation: "$(System.DefaultWorkingDirectory)/**/site/jacoco/jacoco.xml"
#    reportDirectory: "$(System.DefaultWorkingDirectory)/**/site/jacoco"
#    failIfCoverageEmpty: true
- bash: echo $(version)
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: "Cobertura"
    summaryFileLocation: "$(System.DefaultWorkingDirectory)/**/site/cobertura/coverage.xml"
    failIfCoverageEmpty: true